language: go
sudo: false
go:
- tip

notifications:
  slack:
    secure: I1G5gwPUlhZ+Z92CQIMI65hlg9c0TdT/mDSM2nbB8OjWqOT1Xoe0D2Tp/8VZGK6zKSWWp286MysRhzT+iCCk2x/xMLLU7fYPCfdYhb/dj/lpn1Rg4wcbKCkXQfpGblU+zvt10P00qm57xAs427Mh6k+WnSdo/32XDfqUVoHOr+Dn2+BJckjuxaEyyibf+ozfCQPVYNNhpqtVa04PnBHHXo3Kaqpip7VRckOkZcm7GKJ2C6fnG7vEjrfD0OMXmq0v87w1NFYkofMnnC7UgO8J8j6B68uIr+x+iiKBzAz5osErpwh7O7NJkB/nmLY/SW77GsqRHqDf/6hCyFzmdNGYtShfD+sy95BiW7GF5vrEDRu5gVnXHfKF/ZCOxnuzHVI+3Hd+yj6omRL8q9AA8zbolAggSynayXiS+KCfhaBwv3o0jGWPieLyh2cJFkuCacMcnlBcqzuir/Xf1if9CHn1YyB2WbY0Nf5dddP6sX1yMrNEHD8o0Mtp+Jb/4VFxygqDwbbj7TEoMAsoje3bekUEPCU8bMkSnVk8EoD87N98pjuYMVUa/YILudI3FXnbBA4cB0kv4juqJvC/JGrzuxoOKamygzpmgWCL8WD75bn6zdkefXgah3EUmgPYiuTt63cv8FGrIZsCuGst7jtuutH/R7eQqvGF7eW1ie3lqY/ych8=

# Coveralls
dd:
  secure: FWOFiRjNOm/RG8U5TSsobNPQsD1/+moTG11XubOpYnhuaWHHpB8W2zzx2J320k/A/yakctP9nMAtN/01HlOZqiMbhfX0awnNI37ueH34pGHlXR2YNq5Oh75F49/zTZ+MKxJOMTC2UJee/YhO9lbuhcj4XEF+Co7aXYJtkEXbkDhb6vrXDkhDoNW7QZDC12PA6qYOa1jxNfWdnVCOPJLCcsn32cj1ojT1N0cvL2YH0ra1Z9UrbemQj5XPyDRlX1A1rUUKmu0gz80uDFsRE+ydTWLszbBqSZ0NY4qSKyvCk7VQpfyjyhDmBdDbGiiewSY9fmk+X3Ikg8fleP5WJqTp08OOL0NvwNK2s2A5cB5l/3e23mDiXUNTJj0ufKVh23EtAU9Bo394jBKloYIXvy4s2Xy7+KuuZnXXrp/PBsJsFcTD02xk1LgGRkyoS4U2j9+aKgDIcZFCIc7YCx8IPxzMLqTiKI4WqlBBIp6bFfSq4j0FBTS01hM+NX5iOFIFvFgykWulATDGmSuhM8asZxKC4LE5q3SAwQXvVBnml0u0/VA+p/39rLC1UliixZ/OTKEE0t1DOlvFlHQGtUGvmRczb6AAiRkxClz1PBCyWv0hM4B92Es1eylHN5r3a31oGqgWp6quMDqW7y3CuNDbeVSOpJtnlsEGokOIdkW8Ha2uIPg=

before_install:
- cd slackbot_onboard
- pwd
- ls
- openssl aes-256-cbc -K $encrypted_6f470b015f2a_key -iv $encrypted_6f470b015f2a_iv
  -in client-secret.json.enc -out client-secret.json -d

install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls

script:
- go test -v -covermode=count -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

deploy:
  provider: gae
  keyfile: client-secret.json
  project: digital-1168
  default: true
  verbosity: debug
  config: "../app.yaml"
  on:
    all_branches: true
    skip_cleanup: true
