language: go
sudo: false
go:
- tip

before_install:
- cd slackbot_onboard
- pwd
- ls
- openssl aes-256-cbc -K $encrypted_6f470b015f2a_key -iv $encrypted_6f470b015f2a_iv
  -in client-secret.json.enc -out client-secret.json -d

install:
-

script:
- echo "No Script to run"

deploy:
  provider: gae
  keyfile: client-secret.json
  project: digital-1168
  default: true
  verbosity: debug
  config: ../app.yaml
  #version: 2
  on:
    all_branches: true
    skip_cleanup: true
    #repo: project-digital/slackbot_onboard
    #tags: true
