language: go
sudo: false
go:
- tip

before_install:
- openssl aes-256-cbc -K $encrypted_ba96527ab683_key -iv $encrypted_ba96527ab683_iv -in client-secret.json.enc -out client-secret.json -d

install:
- 
script:
- echo "No Script to run"

deploy:
  provider: gae
  keyfile: client-secret.json
  project: digital-1168
  default: true
  verbosity: debug
  skip_cleanup: true
  #config: "./app.yaml"
  on:
    all_branches: true

notifications:
  slack:
    secure: I1G5gwPUlhZ+Z92CQIMI65hlg9c0TdT/mDSM2nbB8OjWqOT1Xoe0D2Tp/8VZGK6zKSWWp286MysRhzT+iCCk2x/xMLLU7fYPCfdYhb/dj/lpn1Rg4wcbKCkXQfpGblU+zvt10P00qm57xAs427Mh6k+WnSdo/32XDfqUVoHOr+Dn2+BJckjuxaEyyibf+ozfCQPVYNNhpqtVa04PnBHHXo3Kaqpip7VRckOkZcm7GKJ2C6fnG7vEjrfD0OMXmq0v87w1NFYkofMnnC7UgO8J8j6B68uIr+x+iiKBzAz5osErpwh7O7NJkB/nmLY/SW77GsqRHqDf/6hCyFzmdNGYtShfD+sy95BiW7GF5vrEDRu5gVnXHfKF/ZCOxnuzHVI+3Hd+yj6omRL8q9AA8zbolAggSynayXiS+KCfhaBwv3o0jGWPieLyh2cJFkuCacMcnlBcqzuir/Xf1if9CHn1YyB2WbY0Nf5dddP6sX1yMrNEHD8o0Mtp+Jb/4VFxygqDwbbj7TEoMAsoje3bekUEPCU8bMkSnVk8EoD87N98pjuYMVUa/YILudI3FXnbBA4cB0kv4juqJvC/JGrzuxoOKamygzpmgWCL8WD75bn6zdkefXgah3EUmgPYiuTt63cv8FGrIZsCuGst7jtuutH/R7eQqvGF7eW1ie3lqY/ych8=
