language: go
sudo: false
go:
- 1.4
- 1.5
- tip

before_install:
- openssl aes-256-cbc -K $encrypted_6f470b015f2a_key -iv $encrypted_6f470b015f2a_iv
  -in client-secret.json.enc -out client-secret.json -d

install:
  
script:
- echo "No Script to run"

deploy:
  provider: gae
  keyfile: client-secret.json
  project: digital-1168
  default: true
  #version: 2
  on:
    all_branches: true
    skip_cleanup: true
    #repo: project-digital/slackbot-onboard
    #tags: true
